# Generated by Django 6.0.4 on 2026-04-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Name of your AI project (e.g., 'RAG Document Analyzer')", max_length=200)),
                ('category', models.CharField(choices=[('agents', 'AI Agents'), ('generative_video', 'Generative Video'), ('generative_image', 'Generative Image'), ('web_app', 'Django Web Apps'), ('other', 'Other')], default='other', help_text='What type of AI project is this?', max_length=50)),
                ('description', models.TextField(help_text='Explain what your AI project does and how you built it. Keep it conversational and real!')),
                ('featured_image', models.ImageField(blank=True, help_text='Upload a screenshot or thumbnail image for your project', null=True, upload_to='projects/images/')),
                ('video_embed_url', models.URLField(blank=True, help_text='Paste the embed URL for YouTube or Vimeo (e.g., https://www.youtube.com/embed/VIDEO_ID)', null=True)),
                ('tools_used', models.CharField(blank=True, help_text="Comma-separated list of tools/libraries (e.g., 'LangChain, OpenAI, Pinecone')", max_length=500)),
                ('project_url', models.URLField(blank=True, help_text='Link to the live project or GitHub repo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Check this to highlight the project on your homepage')),
            ],
            options={
                'verbose_name': 'AI Project',
                'verbose_name_plural': 'AI Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
