# Generated by Django 6.0.4 on 2026-04-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('experience_type', models.CharField(choices=[('work', 'Work Experience'), ('education', 'Education'), ('leadership', 'Leadership')], default='work', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for current role', null=True)),
                ('description', models.TextField(help_text='Job description and achievements (one per line)')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(help_text='One-sentence summary of the project', max_length=500)),
                ('business_problem', models.TextField(help_text='What problem does this solve?')),
                ('description', models.TextField(help_text='Full project description')),
                ('category', models.CharField(choices=[('chatbot', 'Chatbot Project'), ('n8n_automation', 'n8n Automation Workflow'), ('langchain_agent', 'LangChain Agent'), ('ml_project', 'Machine Learning Project'), ('django_app', 'Django Web Application'), ('google_ai', 'Google AI Studio Project'), ('other', 'Other')], default='other', max_length=50)),
                ('tools_used', models.CharField(help_text='Comma-separated: Python, Django, etc.', max_length=500)),
                ('key_features', models.TextField(help_text='Key features (one per line)')),
                ('your_role', models.TextField(help_text='Your specific role and contributions')),
                ('biggest_challenge', models.TextField(help_text='What was your biggest challenge?')),
                ('lessons_learned', models.TextField(help_text='What did you learn from this project?')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('video_embed_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0, help_text='Order of display (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text='Your professional title/headline', max_length=300)),
                ('bio', models.TextField(help_text='Your professional biography (2-3 sentences)')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('resume_file', models.FileField(blank=True, help_text='PDF resume', null=True, upload_to='resume/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('business', 'Business'), ('soft', 'Soft Skills'), ('language', 'Language')], default='technical', max_length=50)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.DeleteModel(
            name='AIProject',
        ),
    ]
